[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "node dist/src/index.js"
healthcheckPath = "/.well-known/arp/index.json"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.volumes]
"/app/data" = "arp-data"
